title: My first github pages sample
author: Ece Simsek
email: ececifter@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An awesome description for your my new page. :)

# social links
twitter_username: ececifter # DO NOT include the @ character, or else the build will fail!
github_username:  forxinecesimsek # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima

